amqp_host:
amqp_port: 31333
amqp_vhost: /dev/data-store
amqp_exchange: irods
amqp_username:
amqp_password:

irods_host: data-dev.cyverse.rocks
irods_port: 1247
irods_username:
irods_password:
irods_zone: cyverse.dev

varnish_urls:
  - "http://127.0.0.1:6081/dav"
  - "http://127.0.0.1:6081/dav-anon"