amqp_host:
amqp_port: 31333
amqp_vhost: /dev/data-store
amqp_exchange: irods
amqp_username:
amqp_password:

irods_host: data-dev.cyverse.rocks
irods_port: 1247
irods_username:
irods_password:
irods_zone: cyverse.dev

varnish_url: "https://data-dev.cyverse.rocks/dav"