amqp_host:
amqp_port: 31333
amqp_vhost: /dev/data-store
amqp_exchange: irods
amqp_username:
amqp_password:

irods_host: data-dev.cyverse.rocks
irods_port: 1247
irods_username:
irods_password:
irods_zone: cyverse.dev

varnish_hosts_override:
  - data-dev.cyverse.rocks
  - data-dev.cyverse.rocks
varnish_urls:
  - "http://localhost/dav"
  - "http://localhost/dav-anon"